service: storybloom

frameworkVersion: '4'

build:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude: ['aws-sdk']
    target: 'node20'
    define: { 'require.resolve': undefined }
    platform: 'node'

custom:
  prefix: ${self:service}-${self:provider.stage}
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
    stages:
      - dev

plugins:
  - serverless-iam-roles-per-function
  - serverless-dynamodb-local
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}  
  profile: storybloom
  environment:
    serviceName: ${self:service}
    stage: ${sls:stage}
    AWS_REGION_NAME: ${opt:region, 'us-east-1'}
    COGNITO_USER_POOL_ID: !Ref UserPool
    # USERS_TABLE: !Ref UsersTable
    # STORIES_TABLE: !Ref StoriesTable
 # --- CHANGE THESE TWO LINES ---
    USERS_TABLE: ${self:custom.prefix}-users
    STORIES_TABLE: ${self:custom.prefix}-stories
    # --- END OF CHANGES ---
    STORY_ASSETS_BUCKET: !Ref StoryAssetsBucket
    IS_OFFLINE: true

functions:
  - ${file(sls-functions/triggers.yml)}
  - ${file(sls-functions/user.yml)}
  - ${file(sls-functions/story.yml)}

resources: ${file(resources.yaml)}